project:
  type: website

website:
  title: "lxh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - music.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



