---
project:
  type: website
  output-dir: docs

website:
  title: "LXH"
  site-url: https://liu-xiaohan.github.io/lxh/
format:
  html:
    theme: cosmo
    css: styles.css
---

My name is Xiaohan, I am a second-year Biostatistics PhD student at the University of Pennsylvania. My interests lie broadly in causal inference, particularly in methods that require as few assumptions on the data generating mechanism as possible. Before joining the PhD program, I obtained my BS in Statistics and Data Science from Carnegie Mellon University where I was fortunate to have received a wonderful undergraduate statistics education. 

For chats about research and potential collaborations, music, or <a href=https://www.goodreads.com/user/show/159086831-xiaohan>books</a>, feel free to reach out at liuxh[at]upenn[dot]edu!

<br>


### Education

- **PhD in Biostatistics**  
  The University of Pennsylvania, Expected 2029
- **BS in Statistics and Data Science (Mathematical Sciences Track)**  
  Carnegie Mellon University, May 2024


<footer style="text-align: center; padding: 10px; font-size: 12px; position: relative; bottom: 50; width: 100%;">
  <p>I took inspiration for this website from others!</p>
</footer>

